name: Frontend Build/Test

on:
 pull_request:
   branches: [feature/*, bugfix/*]
   paths:
     - 'frontend/**'

jobs:

 build:
  runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: ./frontend/app

  strategy:
    matrix:
      node-version: [16.x]

  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install -g @angular/cli
    - run: ng test
    - run: ng lint 

 ImageTest:
  runs-on: ubuntu-latest
  needs: build
  defaults:
    run:
      working-directory: ./frontend/app

  steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Build Docker image frontend
      run: |
            docker build . --tag ghcr.io/wiltoninfra/frontend:latest    