name: Backend Build/Test

on:
 pull_request:
   branches: [feature/*, bugfix/*]
   paths:
     - 'backend/**'

jobs:
 build:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./backend/app

  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Package
      run: mvn test    

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

 Test:
  runs-on: ubuntu-latest
  needs: build
  defaults:
    run:
      working-directory: ./backend/app

  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Package
      run: mvn test

 ImageTest:
  runs-on: ubuntu-latest
  needs: build
  defaults:
    run:
      working-directory: ./backend/app

  steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Build Docker image backend
      run: |
            docker build . --tag ghcr.io/wiltoninfra/backend-spring:latest