name: cd-backend-build-deploy

on:
 push:
   branches: [main]
   paths:
     - 'backend/**'

jobs:
 build:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./backend/app

  steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Package
      run: mvn test    

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

 ImageBuildPush:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write  
  needs: build
  defaults:
    run:
      working-directory: ./backend

  steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: wiltoninfra/backend-app:latest