name: cd-backend-build-deploy

on:
 push:
   branches: [main]
   paths:
     - 'backend/**'

jobs:
 build:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./backend/app

  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: tag_version
      uses: miguelfito/github-bump-and-tag-action@v1
      with:
        github_token: "${{ secrets.CI_GITHUB_TOKEN }}"

    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: "${{ secrets.CI_GITHUB_TOKEN }}"
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Package
      run: mvn test    

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

 ImageBuildPush:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write  
  needs: build
  defaults:
    run:
      working-directory: ./backend

  steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/wiltoninfra/backend

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./backend
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }} 