name: cd-frontend-build-deploy

on:
  push:
    branches: [main]
    paths:
     - 'frontend/**'

jobs:

 build:
  runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: ./frontend/app

  strategy:
    matrix:
      node-version: [16.x]

  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm install -g @angular/cli
    - run: ng test --watch=false --browsers=ChromeHeadless
      continue-on-error: true

 ImageTest:
  runs-on: ubuntu-latest
  
  needs: build

  steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_GITHUB_TOKEN }}

    - run: ls -lsa

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/Dockerfile
        push: true
        tags: wiltoninfra/desafio-iac/frontend-app:latest