name: cd-frontend-build-deploy

on:
  push:
    branches: [main]
    paths:
     - 'frontend/**'

jobs:

 build:
  runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: ./frontend/app

  strategy:
    matrix:
      node-version: [16.x]

  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm install -g @angular/cli
    - run: ng test --watch=false --browsers=ChromeHeadless
      continue-on-error: true

 ImageTest:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write  
  needs: build
  defaults:
    run:
      working-directory: ./frontend

  steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/wiltoninfra/frontend

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}