name: cd-frontend-build-deploy

on:
 push:
   branches: [main]
   paths:
     - 'frontend/**'

jobs:
 Test:
  if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./frontend/app

  strategy:
    matrix:
      node-version: [16.x]

  steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag
      uses: RueLaLa/auto-tagger@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PR_NUMBER: ${{ github.event.number }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalando dependencias
      run: npm install   

    - name: Intalando angular/cli
      run: npm install -g @angular/cli

    - name: Teste Software
      run: ng build --watch --configuration development


 ImageTest:
  runs-on: ubuntu-latest
  needs: build
  defaults:
    run:
      working-directory: ./frontend

  steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build/Push Docker image frontend
      run: |
            docker build . --tag ghcr.io/wiltoninfra/frontend-spring:latest
            docker run ghcr.io/wiltoninfra/frontend-spring:latest