name: cd-frontend-build-deploy

on:
 push:
   branches: [main]
 pull_request:
   branches: [feature/*, bugfix/*]
   paths:
     - 'frontend/**'

jobs:
 build:
  if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./frontend/app

  steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag
      uses: RueLaLa/auto-tagger@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PR_NUMBER: ${{ github.event.number }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Package
      run: mvn test    

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

 Test:
  runs-on: ubuntu-latest
  needs: build
  defaults:
    run:
      working-directory: ./frontend/app

  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test Package
      run: mvn test

 ImageTest:
  runs-on: ubuntu-latest
  needs: build
  defaults:
    run:
      working-directory: ./frontend/app

  steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build/Push Docker image frontend
      run: |
            docker build . --tag ghcr.io/wiltoninfra/frontend-spring:latest
            docker run ghcr.io/wiltoninfra/frontend-spring:latest
            docker push ghcr.io/wiltoninfra/frontend-spring:latest  