name: cd-kubernetes

on:
 push:
   branches: [main]
   paths:
     - 'k8s/**'

jobs:
  deploy-k8s-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./k8s
    steps:
      - uses: actions/checkout@v3

      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=environments/dev.tfvars -lock=false -out plan.tfplan | grep -E '(^.*[#~+-] .*|^[[:punct:]]|Plan)'

      - name: Save Plan JSON
        run: echo '${{ steps.show.outputs.stdout }}' > plan.json

      - name: Resume terraform
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization 🚀 \`${{ steps.init.outcome }}\`
            #### Terraform Validation ✅ \`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📜 \`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        id: apply
        run: terraform apply -var-file=environments/dev.tfvars -lock=false -out plan.tfplan | grep -E '(^.*[#~+-] .*|^[[:punct:]]|Plan)'
