name: ci-iac-terraform validate

on:
  pull_request:
    branches: [main]
    paths:
      - 'iac/**'

jobs:
  terraform-checklist:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac
    env:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      TF_LOG: trace

    steps:
      - uses: actions/checkout@v3

      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=environments/dev.tfvars -lock=false -out plan.tfplan | grep -E '(^.*[#~+-] .*|^[[:punct:]]|Plan)'

      - name: Save Plan JSON
        run: echo '${{ steps.show.outputs.stdout }}' > plan.json

      - name: Resume terraform
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization 🚀 \`${{ steps.init.outcome }}\`
            #### Terraform Validation ✅ \`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📜 \`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  finops-costs:
    runs-on: ubuntu-latest
    env:
      TF_ROOT: ./iac
    needs: terraform-checklist
    steps:
    
      - uses: actions/checkout@v3

      - name: "Install terraform"
        uses:  hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -var-file=environments/dev.tfvars -lock=false -out plan.tfplan | grep -E '(^.*[#~+-] .*|^[[:punct:]]|Plan)'
        continue-on-error: true

      - name: Terraform show
        run: terraform show -json plan.tfplan > plan.json
        continue-on-error: true

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                                    --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Run infracost diff
        id: infracost
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: |
          infracost diff --path=${TF_ROOT} \
                        --format=json \
                        --compare-to=/tmp/infracost-base.json \
                        --out-file=/tmp/infracost.json

      - name: Post Infracost comment
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}    
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                    --repo=wiltoninfra/desafio-iac \
                                    --github-token=${{ secrets.CI_GITHUB_TOKEN }} \
                                    --pull-request=${{github.event.pull_request.number}} \
                                    --behavior=update

  security-scans:
    runs-on: ubuntu-latest
    needs: terraform-checklist
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: "Install terraform"
      uses:  hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file=environments/dev.tfvars -lock=false -out plan.tfplan | grep -E '(^.*[#~+-] .*|^[[:punct:]]|Plan)'

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@v12.873.0
      with:
        directory: .
        framework: terraform
      continue-on-error: true

    - name: Run tfsec action
      id: tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@main
      with:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}
      continue-on-error: true